apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
      - image: yandex/clickhouse-server:19.17
        name: clickhouse
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: sentry-clickhouse
        - mountPath: /var/log/clickhouse-server
          name: sentry-clickhouse-log
      restartPolicy: Always
      volumes:
      - name: sentry-clickhouse
        persistentVolumeClaim:
          claimName: sentry-clickhouse
      - name: sentry-clickhouse-log
        persistentVolumeClaim:
          claimName: sentry-clickhouse-log
status: {}
