apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: symbolicator-cleanup
  name: symbolicator-cleanup
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: symbolicator-cleanup
    spec:
      containers:
      - args:
        - 55 23 * * * gosu symbolicator symbolicator cleanup
        image: symbolicator-cleanup-onpremise-local
        name: symbolicator-cleanup
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: sentry-symbolicator
      restartPolicy: Always
      volumes:
      - name: sentry-symbolicator
        persistentVolumeClaim:
          claimName: sentry-symbolicator
status: {}
